// This file is auto-generated by processing scraped transparency data.
// Do not edit this file directly, modify the scraper scripts or generator instead.

export interface TransparencyLink {
  text: string;
  url: string;
}

export interface TransparencyCategory {
  id: string;
  labelEn: string;
  labelFil: string;
  descriptionEn: string;
  descriptionFil: string;
  links: TransparencyLink[];
}

export const transparencyCategories: TransparencyCategory[] = [
  {
    "id": "mandate-officials",
    "labelEn": "Agency's Mandate, Vision, Mission and List of Officials",
    "labelFil": "Mandato, Bisyon, Misyon at Talaan ng mga Opisyal",
    "descriptionEn": "MMDA's foundational mandate, organizational structure, vision, mission, and the directory of key agency officials.",
    "descriptionFil": "Ang batayang mandato, istrukturang organisasyonal, bisyon, misyon, at direktoryo ng mga pangunahing opisyal ng MMDA.",
    "links": [
      {
        "text": "Organizational Chart",
        "url": "https://mmda.gov.ph/images/pdf/Transparency/II/mmda-Organizational_chart.pdf"
      },
      {
        "text": "Quality Policy Statement",
        "url": "https://mmda.gov.ph/images/pdf/Transparency/qms/2021/QM04.pdf"
      },
      {
        "text": "FY 2013",
        "url": "https://mmda.gov.ph/images/pdf/Transparency/II/Certificate_of_Compliance_General_Appropriations_Act_FY_2013.pdf"
      },
      {
        "text": "FY 2012",
        "url": "https://mmda.gov.ph/images/pdf/Transparency/IX/Annex1.pdf"
      },
      {
        "text": "FY 2014",
        "url": "https://mmda.gov.ph/images/pdf/Transparency/II/Cert-of-SALN-2014.pdf"
      },
      {
        "text": "FY 2013",
        "url": "https://mmda.gov.ph/images/pdf/Transparency/II/compliance-2013.pdf"
      }
    ]
  },
  {
    "id": "financial-reports",
    "labelEn": "Annual Financial Reports",
    "labelFil": "Mga Taunang Ulat sa Pinansyal",
    "descriptionEn": "Budget and Financial Accountability Reports (BFARs), including disbursement reports, financial statements, and receipts.",
    "descriptionFil": "Mga Ulat sa Pananagutang Badyet at Pinansyal (BFARs), kabilang ang mga ulat ng disbursement, financial statement, at resibo.",
    "links": [
      {
        "text": "Current Appropriation",
        "url": "https://mmda.gov.ph/10-transparency/1524-summary-of-appropriations-allotments-obligations-disbursement-and-balances.html"
      },
      {
        "text": "Continuing Appropriation",
        "url": "https://mmda.gov.ph/transparency/annual-reports-financial/10-transparency/3844-summary-of-appropriations-allotments-obligations-disbursement-and-balances-continuing.html"
      },
      {
        "text": "Current Appropriation",
        "url": "https://mmda.gov.ph/10-transparency/1525-summary-of-appropriations-allotments-obligations-disbursements-and-balances-by-object-of-expenditures.html"
      },
      {
        "text": "Continuing Appropriation",
        "url": "https://mmda.gov.ph/transparency/annual-reports-financial/10-transparency/3848-summary-of-appropriations-allotments-obligations-disbursements-and-balances-by-object-of-expenditures-continuing.html"
      },
      {
        "text": "Monthly Report of Disbursement Period (FAR No.4)",
        "url": "https://mmda.gov.ph/10-transparency/1533-monthly-report-of-disbursement-period.html"
      },
      {
        "text": "Quarterly Physical Report of Operation (BAR No. 1)",
        "url": "https://mmda.gov.ph/10-transparency/1885-quarterly-physical-report-of-operation-bar-no-1.html"
      },
      {
        "text": "Quarterly Report of Revenue and Other Receipts (FAR No. 5)",
        "url": "https://mmda.gov.ph/10-transparency/1531-quarterly-report-of-revenue-and-other-receipts-far-no-5.html"
      },
      {
        "text": "Statement of Financial Performance",
        "url": "https://mmda.gov.ph/10-transparency/1526-report-of-statement-of-financial-performance.html"
      },
      {
        "text": "Physical and Financial Plans (Bed No.1 and Bed No. 2)",
        "url": "https://mmda.gov.ph/10-transparency/1527-physical-and-financial-plans.html"
      },
      {
        "text": "Report of Ageing of Cash Advance (Schedule of Advances to Officers and Employees)",
        "url": "https://mmda.gov.ph/10-transparency/1528-schedule-of-advances-to-officers-and-employees.html"
      },
      {
        "text": "Report of Financial Position",
        "url": "https://mmda.gov.ph/10-transparency/1529-report-of-financial-position.html"
      },
      {
        "text": "Statement of Cash Flows",
        "url": "https://mmda.gov.ph/10-transparency/1530-statement-of-cash-flows.html"
      },
      {
        "text": "Financial Report of Operations",
        "url": "https://mmda.gov.ph/10-transparency/1532-financial-report-of-operations.html"
      },
      {
        "text": "List of Agency Budget Matrix / SARO / Sub-Allotment Release Orders (FAR No. 1B)",
        "url": "https://mmda.gov.ph/10-transparency/1534-list-of-agency-budget-matrix-saro-sub-allotment-release-orders-far-no-1b.html"
      },
      {
        "text": "Advice of NCA Issued",
        "url": "https://mmda.gov.ph/10-transparency/1535-advice-of-nca-issued.html"
      },
      {
        "text": "Aging of Due and Demandable Obligations (FAR No. 3)",
        "url": "https://mmda.gov.ph/10-transparency/1536-aging-of-due-and-demandable-obligations-far-no-3.html"
      },
      {
        "text": "Statement of Change in Net Assets/Equity",
        "url": "https://mmda.gov.ph/10-transparency/1537-statement-of-change-in-net-assets-equity.html"
      },
      {
        "text": "Trial Balance",
        "url": "https://mmda.gov.ph/10-transparency/2138-trial-balance.html"
      },
      {
        "text": "Statement of Comparison of Budget and Actual Amount",
        "url": "https://mmda.gov.ph/transparency/annual-reports-financial/10-transparency/2757-statement-of-comparison-of-budget-and-actual-amount.html"
      },
      {
        "text": "Foreign Assisted Project (World Bank)",
        "url": "https://mmda.gov.ph/transparency/annual-reports-financial/10-transparency/4006-foreign-assisted-project-world-bank.html"
      }
    ]
  },
  {
    "id": "budget-targets",
    "labelEn": "DBM Approved Budget and Targets",
    "labelFil": "Inaprubahang Badyet at mga Target ng DBM",
    "descriptionEn": "Department of Budget and Management (DBM) approved budgets, physical targets, MFOs, and disaster risk reduction fund utilization.",
    "descriptionFil": "Mga inaprubahang badyet ng DBM, pisikal na target, MFOs, at paggamit ng pondo para sa bawas-panganib sa sakuna.",
    "links": [
      {
        "text": "Approved Budget and Target",
        "url": "https://mmda.gov.ph/83-transparency/dbm-approved-targets/4680-approved-budget-and-targets.html"
      },
      {
        "text": "Targets/MFOs/GAA Targets",
        "url": "https://mmda.gov.ph/83-transparency/dbm-approved-targets/4681-targets-mfo-gaa.html"
      },
      {
        "text": "Program Profiles (Form A) and Matrix of Indicator Definition (MID)",
        "url": "https://mmda.gov.ph/83-transparency/dbm-approved-targets/4682-program-profiles-mid.html"
      },
      {
        "text": "Department Targets on Key Programs and Project Targets",
        "url": "https://mmda.gov.ph/83-transparency/dbm-approved-targets/4683-major-final-output-mfo.html"
      },
      {
        "text": "Receipt and Utilization of DRRMF",
        "url": "https://mmda.gov.ph/83-transparency/dbm-approved-targets/4684-receipt-and-utilization-of-drrmf.html"
      },
      {
        "text": "Budget Utilization Report",
        "url": "https://mmda.gov.ph/83-transparency/dbm-approved-targets/4685-budget-utilization-report.html"
      }
    ]
  },
  {
    "id": "ppa-beneficiaries",
    "labelEn": "PPA - Beneficiaries & Status of Implementation",
    "labelFil": "PPA - Mga Benepisyaryo at Katayuan ng Pagpapatupad",
    "descriptionEn": "Programs, projects, and beneficiaries identified under special provisions, alongside their official implementation status.",
    "descriptionFil": "Mga programa, proyekto, at benepisyaryo na tinukoy sa ilalim ng mga espesyal na probisyon, kasama ang katayuan ng pagpapatupad.",
    "links": [
      {
        "text": "Flood Control and Sewerage Management Office",
        "url": "https://mmda.gov.ph/images/pdf/Transparency/VII/2020-FCSMO-Project-and-beneficiaries.pdf"
      },
      {
        "text": "Solid Waste Management Office",
        "url": "https://mmda.gov.ph/images/pdf/Transparency/VII/2020-SWMO-Project-and-beneficiaries.pdf"
      },
      {
        "text": "Flood Control and Sewerage Management Office",
        "url": "https://mmda.gov.ph/images/pdf/Transparency/VII/2019-FCSMO-Project-and-Beneficiaries.pdf"
      },
      {
        "text": "Solid Waste Management Office",
        "url": "https://mmda.gov.ph/images/pdf/Transparency/VII/2019-SWMO-Project-and-beneficiaries.pdf"
      },
      {
        "text": "Flood Control and Sewerage Management Office",
        "url": "https://mmda.gov.ph/images/pdf/Transparency/VII/FCSMO-2018-PROJECTS.pdf"
      },
      {
        "text": "Solid Waste Management Office",
        "url": "https://mmda.gov.ph/images/pdf/Transparency/VII/SWMO-2018-PROJECTS.pdf"
      },
      {
        "text": "Traffic Engineering Center",
        "url": "https://mmda.gov.ph/images/pdf/Transparency/VII/TDO-2018-PROJECTS.pdf"
      },
      {
        "text": "Flood Control and Sewerage Management Office",
        "url": "https://mmda.gov.ph/images/pdf/Transparency/VII/FCSMO-2017-PROJECTS.pdf"
      },
      {
        "text": "Solid Waste Management Office",
        "url": "https://mmda.gov.ph/images/pdf/Transparency/VII/SWMO-2017-PROJECTS.pdf"
      },
      {
        "text": "Traffic Engineering Center",
        "url": "https://mmda.gov.ph/images/pdf/Transparency/VII/TDO-2017-PROJECTS.pdf"
      },
      {
        "text": "Flood Control and Sewerage Management Office",
        "url": "https://mmda.gov.ph/images/pdf/Transparency/PBB-Files/flood-control-projects2016.pdf"
      },
      {
        "text": "Solid Waste Management Office",
        "url": "https://mmda.gov.ph/images/pdf/Transparency/PBB-Files/SWMO-projects-2016-final.pdf"
      },
      {
        "text": "Traffic Engineering Center",
        "url": "https://mmda.gov.ph/images/pdf/Transparency/PBB-Files/tdo-tec-project-2016.pdf"
      },
      {
        "text": "Flood Control and Sewerage Management Office",
        "url": "https://mmda.gov.ph/images/pdf/Transparency/PBB-Files/fcsmo_projects-programs-2015.pdf"
      },
      {
        "text": "Solid Waste Management Office",
        "url": "https://mmda.gov.ph/images/pdf/Transparency/PBB-Files/swmo_projects-programs-2015.pdf"
      },
      {
        "text": "Traffic Engineering Center",
        "url": "https://mmda.gov.ph/images/pdf/Transparency/PBB-Files/tec_projects-programs-2015.pdf"
      },
      {
        "text": "Flood Control and Sewerage Management Office",
        "url": "https://mmda.gov.ph/images/pdf/Transparency/PBB-Files/FCSMO-Projects.pdf"
      },
      {
        "text": "Solid Waste Management Office",
        "url": "https://mmda.gov.ph/images/pdf/Transparency/PBB-Files/SWMO-Projects.pdf"
      },
      {
        "text": "Traffic Engineering Center",
        "url": "https://mmda.gov.ph/images/pdf/Transparency/PBB-Files/TEC-Projects.pdf"
      },
      {
        "text": "FY 2013",
        "url": "https://mmda.gov.ph/images/pdf/Transparency/VI/EGR-Major-Programs-2013.pdf"
      }
    ]
  },
  {
    "id": "procurement-plan",
    "labelEn": "Annual Procurement Plan",
    "labelFil": "Taunang Plano sa Pamimili",
    "descriptionEn": "Annual Procurement Plans (APP), procurement monitoring reports (PMR), and contracts awarded for goods and infrastructure.",
    "descriptionFil": "Mga Taunang Plano sa Pamimili (APP), procurement monitoring reports (PMR), at mga kontratang iginawad para sa mga kalakal at imprastraktura.",
    "links": [
      {
        "text": "Approved Annual Procurement Plan",
        "url": "https://mmda.gov.ph/images/pdf/Transparency/VIII/APP-2023.pdf"
      },
      {
        "text": "For Common Use Supplies and Equipment",
        "url": "https://mmda.gov.ph/images/pdf/Transparency/VIII/APP_CSE-2023.pdf"
      },
      {
        "text": "Indicative Annual Procurement Plan for Goods",
        "url": "https://mmda.gov.ph/images/pdf/Transparency/VIII/Indicative-APP-Goods-2023.pdf"
      },
      {
        "text": "Indicative Annual Procurement Plan for Infrastracture",
        "url": "https://mmda.gov.ph/images/pdf/Transparency/VIII/Indicative-APP-Infra-2023.pdf"
      },
      {
        "text": "For Goods and Services",
        "url": "https://mmda.gov.ph/images/pdf/Transparency/VIII/APP-GoodsServices2022.pdf"
      },
      {
        "text": "For Infrastracture Projects",
        "url": "https://mmda.gov.ph/images/pdf/Transparency/VIII/APP-Infra2022.pdf"
      },
      {
        "text": "For Common Use and  Equipment",
        "url": "https://mmda.gov.ph/images/pdf/Transparency/VIII/APP-CSE2022.pdf"
      },
      {
        "text": "Indicative Annual Procurement Plan for Goods",
        "url": "https://mmda.gov.ph/images/pdf/Transparency/VIII/IndicativeAPPGoods-2022.pdf"
      },
      {
        "text": "Indicative Annual Procurement Plan for Infrastracture",
        "url": "https://mmda.gov.ph/images/pdf/Transparency/VIII/IndicativeAPPINFRA-2022.pdf"
      },
      {
        "text": "For Goods and Services",
        "url": "https://mmda.gov.ph/images/pdf/Transparency/VIII/APP-2021-GOODS-AND-SERVICES.pdf"
      },
      {
        "text": "For Infrastracture Projects",
        "url": "https://mmda.gov.ph/images/pdf/Transparency/VIII/APP-2021-INFRA.pdf"
      },
      {
        "text": "For Common Use and  Equipment",
        "url": "https://mmda.gov.ph/images/pdf/Transparency/VIII/APP-CSE-2021_0001.pdf"
      },
      {
        "text": "Indicative Annual Procurement Plan for Goods",
        "url": "https://mmda.gov.ph/images/pdf/Transparency/VIII/INDICATIVE-APP-2021-GOODS.pdf"
      },
      {
        "text": "Indicative Annual Procurement Plan for Infrastracture",
        "url": "https://mmda.gov.ph/images/pdf/Transparency/VIII/INDICATIVE-APP-2021-INFRA.pdf"
      },
      {
        "text": "Tier 1",
        "url": "https://mmda.gov.ph/images/pdf/Transparency/VIII/app-goods-2020-tier1.pdf"
      },
      {
        "text": "Tier 2",
        "url": "https://mmda.gov.ph/images/pdf/Transparency/VIII/app-goods-2020-tier2.pdf"
      },
      {
        "text": "Approved APP FY 2020",
        "url": "https://mmda.gov.ph/images/pdf/Transparency/VIII/APP-2020-GOODS.pdf"
      },
      {
        "text": "Tier 1",
        "url": "https://mmda.gov.ph/images/pdf/Transparency/VIII/app-infra-2020-tier1.pdf"
      },
      {
        "text": "Tier 2",
        "url": "https://mmda.gov.ph/images/pdf/Transparency/VIII/app-infra-2020-tier-2.pdf"
      },
      {
        "text": "Approved APP FY 2020",
        "url": "https://mmda.gov.ph/images/pdf/Transparency/VIII/APP-FY2020-Infra.pdf"
      }
    ]
  },
  {
    "id": "qms-iso-certification",
    "labelEn": "QMS ISO Certification (ICB)",
    "labelFil": "Sertipikasyon ng QMS ISO (ICB)",
    "descriptionEn": "ISO Certification of MMDA core processes by international certifying bodies, verifying quality management compliance.",
    "descriptionFil": "Sertipikasyon ng ISO sa mga pangunahing proseso ng MMDA mula sa mga international certifying body para sa pamamahala ng kalidad.",
    "links": [
      {
        "text": "FY 2021",
        "url": "https://mmda.gov.ph/images/pdf/Transparency/VII/CERTIFICATION-2021.pdf"
      },
      {
        "text": "Attestation (2020)",
        "url": "https://mmda.gov.ph/images/pdf/Transparency/VII/attestation-2020.pdf"
      },
      {
        "text": "FY 2019 (May)",
        "url": "https://mmda.gov.ph/images/pdf/Transparency/VII/ISO-Certification-5-9-2019.pdf"
      },
      {
        "text": "FY 2018",
        "url": "https://mmda.gov.ph/images/pdf/Transparency/VIII/MMDA-Cert.pdf"
      }
    ]
  },
  {
    "id": "ranking-delivery-units",
    "labelEn": "System of Ranking Delivery Units and Individual",
    "labelFil": "Sistema ng Pagraranggo ng mga Delivery Unit",
    "descriptionEn": "System and guidelines for ranking MMDA delivery units and individual employees for performance-based rewards.",
    "descriptionFil": "Sistema at mga alituntunin para sa pagraranggo ng mga delivery unit at indibidwal na empleyado ng MMDA para sa performance-based rewards.",
    "links": [
      {
        "text": "Internal Guidelines",
        "url": "https://mmda.gov.ph/images/pdf/Transparency/X/GUIDELINES-FOR-THE-FY-2022-PBB.pdf"
      },
      {
        "text": "Amendment Item No. 6",
        "url": "https://mmda.gov.ph/images/pdf/Transparency/X/ADDENDUM-GUIDELINES-FOR-FY-2022.pdf"
      },
      {
        "text": "Internal Guidelines",
        "url": "https://mmda.gov.ph/images/pdf/Transparency/X/2021-Guidelines.pdf"
      },
      {
        "text": "Amendment Item No. 6",
        "url": "https://mmda.gov.ph/images/pdf/Transparency/VII/Amendment-Item-No6.pdf"
      },
      {
        "text": "FY 2020",
        "url": "https://mmda.gov.ph/images/pdf/Transparency/X/2020-System-of-Ranking.pdf"
      },
      {
        "text": "FY 2022",
        "url": "https://mmda.gov.ph/images/pdf/Transparency/PBB-Files/Form1-FY2022.pdf"
      },
      {
        "text": "FY 2021",
        "url": "https://mmda.gov.ph/images/pdf/Transparency/PBB-Files/Form1-FY2021.pdf"
      },
      {
        "text": "FY 2020",
        "url": "https://mmda.gov.ph/images/pdf/Transparency/PBB-Files/FY2020-Form1_0.pdf"
      },
      {
        "text": "FY 2019",
        "url": "https://mmda.gov.ph/images/pdf/Transparency/PBB-Files/pbb-2019/2019-form-1-0-and-summary.pdf"
      },
      {
        "text": "FY 2020",
        "url": "https://mmda.gov.ph/images/pdf/Transparency/X/MMDA_2020_Scorecard.pdf"
      },
      {
        "text": "FY 2019",
        "url": "https://mmda.gov.ph/images/pdf/Transparency/X/MMDA_2019_Scorecard.pdf"
      },
      {
        "text": "FY 2018",
        "url": "https://mmda.gov.ph/images/pdf/Transparency/X/2018_Scorecard.pdf"
      }
    ]
  },
  {
    "id": "review-compliance-procedure",
    "labelEn": "Agency Review and Compliance Procedure",
    "labelFil": "Pamamaraan sa Pagsusuri at Pagsunod ng Ahensya",
    "descriptionEn": "Procedural guidelines for the review and compliance of Statements of Assets, Liabilities, and Net Worth (SALN).",
    "descriptionFil": "Mga alituntunin sa pamamaraan para sa pagsusuri at pagsunod sa Statements of Assets, Liabilities, and Net Worth (SALN).",
    "links": [
      {
        "text": "FY 2022",
        "url": "https://mmda.gov.ph/images/pdf/Transparency/X/AgencyReview-2022.pdf"
      },
      {
        "text": "FY 2021",
        "url": "https://mmda.gov.ph/images/pdf/Transparency/X/FY-2021-AgencyReview.pdf"
      },
      {
        "text": "FY 2020",
        "url": "https://mmda.gov.ph/images/pdf/Transparency/X/2020-SALN-Review-Compliance-Procedure.pdf"
      },
      {
        "text": "FY 2019",
        "url": "https://mmda.gov.ph/images/pdf/Transparency/X/2019-SALN-Review-Compliance-Procedure.pdf"
      },
      {
        "text": "FY 2018",
        "url": "https://mmda.gov.ph/images/pdf/Transparency/X/2018-SALN-Review-Compliance-Procedure-final.pdf"
      },
      {
        "text": "SALN-RCC",
        "url": "https://mmda.gov.ph/images/pdf/Transparency/X/SALN-RCC.pdf"
      }
    ]
  },
  {
    "id": "foi-manual",
    "labelEn": "Freedom of Information People's Manual",
    "labelFil": "Manwal ng Freedom of Information",
    "descriptionEn": "MMDA Freedom of Information People's Manual, compliance certificates, and consolidated tracking logs.",
    "descriptionFil": "Ang Freedom of Information People's Manual ng MMDA, mga sertipiko ng pagsunod, at consolidated tracking logs.",
    "links": [
      {
        "text": "FOI Manual",
        "url": "https://mmda.gov.ph/images/pdf/Transparency/PBB-Files/FOI-Manual-January2024.pdf"
      },
      {
        "text": "FOI Reports",
        "url": "https://mmda.gov.ph/images/pdf/Transparency/PBB-Files/2017-2024_Consolidated_MMDA_FOI_Reports.xlsx"
      },
      {
        "text": "FY 2023",
        "url": "https://mmda.gov.ph/images/pdf/Transparency/PBB-Files/FOI-PBB-2023-COMPLIANCE.pdf"
      },
      {
        "text": "FY 2022",
        "url": "https://mmda.gov.ph/images/pdf/Transparency/PBB-Files/2022_Certificate-Compliance.pdf"
      },
      {
        "text": "FY 2017",
        "url": "https://mmda.gov.ph/images/pdf/Transparency/PBB-Files/FOI-Certicate-of-Compliance.pdf"
      }
    ]
  },
  {
    "id": "citizen-charter",
    "labelEn": "MMDA Citizen's Charter",
    "labelFil": "Citizen's Charter ng MMDA",
    "descriptionEn": "Official Citizen's Charter handbook editions and certificates of compliance with ease of doing business laws.",
    "descriptionFil": "Mga opisyal na edisyon ng Citizen's Charter handbook at mga sertipiko ng pagsunod sa mga batas para sa kadalian ng negosyo.",
    "links": [
      {
        "text": "1st Edition",
        "url": "https://mmda.gov.ph/images/pdf/Transparency/II/2020/FINAL_MMDA-CITIZENS-CHARTER-HANDBOOK1.pdf"
      },
      {
        "text": "2nd Edition",
        "url": "https://mmda.gov.ph/images/pdf/Transparency/II/2022/FINAL_2022_2ND-EDITION_Standard-Citizen-Charter.pdf"
      },
      {
        "text": "Improvement on Citizens Charter For CY 2017",
        "url": "https://mmda.gov.ph/images/pdf/Transparency/II/CITIZENS-CHARTER-IMPROVEMENT-2017.pdf"
      },
      {
        "text": "FY 2020",
        "url": "https://mmda.gov.ph/images/pdf/Transparency/II/2020/Certificate-of-Compliance-ARTA-2020.pdf"
      },
      {
        "text": "FY 2019",
        "url": "https://mmda.gov.ph/images/pdf/Transparency/II/2019-CoC-Final.pdf"
      },
      {
        "text": "FY 2018",
        "url": "https://mmda.gov.ph/images/pdf/Transparency/II/2018-CoC-FS-final.pdf"
      },
      {
        "text": "FY 2017",
        "url": "https://mmda.gov.ph/images/pdf/Transparency/II/2017-CoC-with-FS.pdf"
      }
    ]
  },
  {
    "id": "status-of-income",
    "labelEn": "Annual Reports on the Status of Income",
    "labelFil": "Mga Taunang Ulat sa Katayuan ng Kita",
    "descriptionEn": "Annual reports on the status of income authorized by law to be deposited outside the National Treasury.",
    "descriptionFil": "Mga taunang ulat sa katayuan ng kita na pinahihintulutan ng batas na ideposito sa labas ng Pambansang Kaban.",
    "links": [
      {
        "text": "FY 2018",
        "url": "https://mmda.gov.ph/images/pdf/Transparency/VII/annual-reports-income-authorize-by-law-2018.pdf"
      },
      {
        "text": "FY 2017",
        "url": "https://mmda.gov.ph/images/pdf/Transparency/VII/annual-reports-status-of-income.pdf"
      }
    ]
  },
  {
    "id": "operations-manual",
    "labelEn": "Operations Manual(ISO:9001)",
    "labelFil": "Manwal ng Operasyon (ISO:9001)",
    "descriptionEn": "MMDA Operations Manual aligned with ISO 9001:2015 Quality Management System standards.",
    "descriptionFil": "Ang Operations Manual ng MMDA na naka-align sa mga pamantayan ng ISO 9001:2015 Quality Management System.",
    "links": [
      {
        "text": "Management Review Meeting Minutes",
        "url": "https://mmda.gov.ph/images/pdf/Transparency/qms/2022/Management-Review-Meeting-minutes-2022.pdf"
      },
      {
        "text": "FY 2022",
        "url": "https://mmda.gov.ph/images/pdf/Transparency/qms/2022/2022-MMDA-Operations-Manual.pdf"
      }
    ]
  },
  {
    "id": "major-programs-projects",
    "labelEn": "Major Programs and Projects in accordance with 5 Keys Results",
    "labelFil": "Mga Pangunahing Programa at Proyekto",
    "descriptionEn": "Detailed physical plan and budget allocation for major programs in flood control, traffic engineering, and solid waste management.",
    "descriptionFil": "Detalyadong pisikal na plano at alokasyon ng badyet para sa mga pangunahing programa sa flood control, traffic engineering, at solid waste.",
    "links": [
      {
        "text": "Project Outlay - List of Flood Control Projects",
        "url": "https://mmda.gov.ph/images/pdf/Transparency/V/Project-Outlay-Flood-Control-Projects.pdf"
      },
      {
        "text": "FY 2015",
        "url": "https://mmda.gov.ph/images/pdf/Transparency/V/Physical-Plan-2015.pdf"
      },
      {
        "text": "FY 2014",
        "url": "https://mmda.gov.ph/images/pdf/Transparency/V/Physical-Plan-2014.pdf"
      },
      {
        "text": "FY 2013",
        "url": "https://mmda.gov.ph/images/pdf/Transparency/V/MMDA-Physical-Plan-2013.pdf"
      },
      {
        "text": "Flood Control and Sewerage Management Office",
        "url": "https://mmda.gov.ph/images/pdf/Transparency/V/Programs-Projects-FCSMO-2014.pdf"
      },
      {
        "text": "Solid Waste Management Office",
        "url": "https://mmda.gov.ph/images/pdf/Transparency/V/Programs-Projects-SWMO-2014.pdf"
      },
      {
        "text": "Traffic Engineering Center",
        "url": "https://mmda.gov.ph/images/pdf/Transparency/V/Programs-Projects-TEC-2014.pdf"
      },
      {
        "text": "MMDA Physical Performance Report for FY 2012 (TDO, SWMO, FCSMO, HPSEPO, OAGMO)",
        "url": "https://mmda.gov.ph/images/pdf/Transparency/V/MMDA-Physical-Performance-2012.pdf"
      },
      {
        "text": "2012 Major Programs and Projects",
        "url": "https://mmda.gov.ph/images/pdf/Transparency/V/MMDA-Major-Programs-and-Projects-2012.pdf"
      }
    ]
  },
  {
    "id": "accomplishment-reports",
    "labelEn": "Accomplishment Reports",
    "labelFil": "Mga Ulat ng Accomplishment",
    "descriptionEn": "MMDA Executive Summary reports, annual accomplishments, and key performance target indicators.",
    "descriptionFil": "Mga Executive Summary report ng MMDA, mga taunang accomplishment, at mga tagapagpahiwatig ng target na pagganap.",
    "links": [
      {
        "text": "Performance Indicator and Performance targets of Bureaus / Delivery Units for FY 2013",
        "url": "https://mmda.gov.ph/images/pdf/Transparency/VII/PerformanceIndicators-PerformanceTargets.zip"
      },
      {
        "text": "PBB MMDA Official Report 2012",
        "url": "https://mmda.gov.ph/images/pdf/Transparency/VII/PBB-MMDAofficialreport-2012.pdf"
      },
      {
        "text": "1st Semester",
        "url": "https://mmda.gov.ph/images/pdf/Transparency/VII/ExecutiveSummary-1stSem2022.pdf"
      },
      {
        "text": "Annual",
        "url": "https://mmda.gov.ph/images/pdf/Transparency/VII/ExecutiveSummary-FY2021.pdf"
      },
      {
        "text": "Annual",
        "url": "https://mmda.gov.ph/images/pdf/Transparency/VII/Executive-Summary-FY2020.pdf"
      },
      {
        "text": "1st Semester",
        "url": "https://mmda.gov.ph/images/pdf/Transparency/VII/Executive-Summary-FY_2020-1st_Semester.pdf"
      },
      {
        "text": "Annual",
        "url": "https://mmda.gov.ph/images/pdf/Transparency/VII/Executive-Summary-CY_2019.pdf"
      },
      {
        "text": "Annual",
        "url": "https://mmda.gov.ph/images/pdf/Transparency/VII/Executive-Summary-CY_2018.pdf"
      },
      {
        "text": "3rd Quarter",
        "url": "https://mmda.gov.ph/images/pdf/Transparency/VII/Executive-Summary-CY_2018-3rdQuarter.pdf"
      },
      {
        "text": "1st Semester",
        "url": "https://mmda.gov.ph/images/pdf/Transparency/VII/Executive-Summary-CY-2018-1st-Semester.pdf"
      },
      {
        "text": "1st Quarter",
        "url": "https://mmda.gov.ph/images/pdf/Transparency/VII/Executive-Summary-CY-2018-1stQuarter.pdf"
      },
      {
        "text": "Annual",
        "url": "https://mmda.gov.ph/images/pdf/Transparency/VII/Executive-Summary-CY-2017-ANNUAL.pdf"
      },
      {
        "text": "3rd Quarter",
        "url": "https://mmda.gov.ph/images/pdf/Transparency/VII/Executive-Summary-3rd-Quarter-2017.pdf"
      },
      {
        "text": "1st Semester",
        "url": "https://mmda.gov.ph/images/pdf/Transparency/VII/Executive-Summary-1st-Semester-2017.pdf"
      },
      {
        "text": "1st Quarter",
        "url": "https://mmda.gov.ph/images/pdf/Transparency/VII/Executive-Summary-1st-Quarter-2017.pdf"
      },
      {
        "text": "Annual",
        "url": "https://mmda.gov.ph/images/pdf/Transparency/VII/Executive-Summary-CY-2016.pdf"
      },
      {
        "text": "3rd Quarter",
        "url": "https://mmda.gov.ph/images/pdf/Transparency/VII/Executive-Summary-3rd-Quarter-2016.pdf"
      },
      {
        "text": "1st Semester",
        "url": "https://mmda.gov.ph/images/pdf/Transparency/VII/Executive-Summary-1st-Semester-2016.pdf"
      },
      {
        "text": "1st Quarter",
        "url": "https://mmda.gov.ph/images/pdf/Transparency/VII/Executive-Summary-1st-Quarter-2016.pdf"
      },
      {
        "text": "Annual",
        "url": "https://mmda.gov.ph/images/pdf/Transparency/VII/Executive-Summary-CY-2015.pdf"
      }
    ]
  },
  {
    "id": "philgeps-compliance",
    "labelEn": "Compliance on PHILGEPS",
    "labelFil": "Pagsunod sa PHILGEPS",
    "descriptionEn": "Certificates of compliance with Philippine Government Electronic Procurement System (PhilGEPS) posting requirements.",
    "descriptionFil": "Mga sertipiko ng pagsunod sa mga kinakailangan sa pag-post sa Philippine Government Electronic Procurement System (PhilGEPS).",
    "links": [
      {
        "text": "MEMORANDUM from BAC SECRETARIAT (Temporary Closure of BAC OFFICE located at third Floor of MMDA Auditorium)",
        "url": "https://mmda.gov.ph/images/pdf/Transparency/IX/2020/memo-temporary-closure.pdf"
      },
      {
        "text": "List of MMDA Resolutions Approved by the Metro Manila Council for 2013",
        "url": "https://mmda.gov.ph/images/pdf/Transparency/IX/2013-MMC-Approved-Reso.pdf"
      },
      {
        "text": "as of June",
        "url": "https://mmda.gov.ph/images/pdf/Transparency/IX/2024/PMR-2024June302024.pdf"
      },
      {
        "text": "as of December",
        "url": "https://mmda.gov.ph/images/pdf/Transparency/IX/2023/PMR-December2023.pdf"
      },
      {
        "text": "as of June",
        "url": "https://mmda.gov.ph/images/pdf/Transparency/IX/2023/PMR-June2023.pdf"
      },
      {
        "text": "as of December",
        "url": "https://mmda.gov.ph/images/pdf/Transparency/IX/2022/PMR-December2022.pdf"
      },
      {
        "text": "as of June",
        "url": "https://mmda.gov.ph/images/pdf/Transparency/IX/2022/PMR-June2022.pdf"
      },
      {
        "text": "FY 2020",
        "url": "https://mmda.gov.ph/images/pdf/Transparency/IX/2020/PMR-2020-GOODS-AND-INFRA.pdf"
      }
    ]
  },
  {
    "id": "pbb-documents",
    "labelEn": "Performance Based Bonus Documents",
    "labelFil": "Mga Dokumento para sa PBB",
    "descriptionEn": "Performance-Based Bonus (PBB) compliance documents, including MFO targets, Form A, Form A-1, and operational justifications.",
    "descriptionFil": "Mga dokumento para sa pagsunod sa Performance-Based Bonus (PBB), kabilang ang MFO targets, Form A, Form A-1, at operational justifications.",
    "links": [
      {
        "text": "Form A",
        "url": "https://mmda.gov.ph/images/pdf/Transparency/X/2015_mfo_sto_gass/Form_A_2015.pdf"
      },
      {
        "text": "Form A- 1",
        "url": "https://mmda.gov.ph/images/pdf/Transparency/X/2015_mfo_sto_gass/Form_A1_2015.pdf"
      },
      {
        "text": "TDO Justification",
        "url": "https://mmda.gov.ph/images/pdf/Transparency/X/2015_mfo_sto_gass/TDO_Justification_2015.pdf"
      },
      {
        "text": "Form B",
        "url": "https://mmda.gov.ph/images/pdf/Transparency/X/2015_mfo_sto_gass/Form_B_2015.pdf"
      },
      {
        "text": "Form C",
        "url": "https://mmda.gov.ph/images/pdf/Transparency/X/2015_mfo_sto_gass/Form_C_2015.pdf"
      },
      {
        "text": "Form A",
        "url": "https://mmda.gov.ph/images/pdf/Transparency/X/2015_mfo_sto_gass/Form-A-SWMO.pdf"
      },
      {
        "text": "Form A1",
        "url": "https://mmda.gov.ph/images/pdf/Transparency/X/2015_mfo_sto_gass/Form-A1-SWMO.pdf"
      },
      {
        "text": "Support to Operation",
        "url": "https://mmda.gov.ph/images/pdf/Transparency/X/2015_mfo_sto_gass/STO_2015.pdf"
      },
      {
        "text": "General Administration and Support Services",
        "url": "https://mmda.gov.ph/images/pdf/Transparency/X/2015_mfo_sto_gass/GASS_2015.pdf"
      },
      {
        "text": "Form 1.0",
        "url": "https://mmda.gov.ph/images/pdf/Transparency/X/2015_mfo_sto_gass/form_1_0_2015.pdf"
      },
      {
        "text": "Form A",
        "url": "https://mmda.gov.ph/images/pdf/Transparency/PBB-Files/FORM-A.pdf"
      },
      {
        "text": "Form A- 1",
        "url": "https://mmda.gov.ph/images/pdf/Transparency/PBB-Files/FORM-A-1.pdf"
      },
      {
        "text": "Form B (MFO)",
        "url": "https://mmda.gov.ph/images/pdf/Transparency/PBB-Files/Major-Operating-Offices-Form-B.pdf"
      },
      {
        "text": "Addendum",
        "url": "https://mmda.gov.ph/images/pdf/Transparency/PBB-Files/Form-B-Additional.pdf"
      },
      {
        "text": "Support to Operation (STO)",
        "url": "https://mmda.gov.ph/images/pdf/Transparency/PBB-Files/STO.pdf"
      },
      {
        "text": "General Administration and Support Services (GASS)",
        "url": "https://mmda.gov.ph/images/pdf/Transparency/PBB-Files/GASS.pdf"
      },
      {
        "text": "Refined Organizational Outcomes and Performance Indicators",
        "url": "https://mmda.gov.ph/images/pdf/Transparency/PBB-Files/Refined-Organizational2014.pdf"
      },
      {
        "text": "Final Approved Form A Contents Enrolled for 2013 PBB",
        "url": "https://mmda.gov.ph/images/pdf/Transparency/X/Final-Approved-Form-A-Contents-2013-PBB.pdf"
      },
      {
        "text": "PBB 2013 Summary (Support to Operations)",
        "url": "https://mmda.gov.ph/images/pdf/Transparency/X/PBB-2013-Summary-STO.pdf"
      },
      {
        "text": "PBB 2013 Summary (General Administration and Support Services)",
        "url": "https://mmda.gov.ph/images/pdf/Transparency/X/PBB-2013-Summary-GASS.pdf"
      }
    ]
  }
];
